version: "3.8"

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "${PORT}:5001"
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - JWT_REFRESH_EXPIRE=${JWT_REFRESH_EXPIRE}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - AUTO_SEED_ADMIN=${AUTO_SEED_ADMIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_PHONE=${ADMIN_PHONE}
    restart: unless-stopped
