apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ${DOCKER_REGISTRY}/auth-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: NODE_ENV
              value: "production"
            - name: MONGOURL
              value: "mongodb://mongodb:27017/food-auth"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRE
              value: "24h"
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_REFRESH_SECRET
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: food-delivery
spec:
  selector:
    app: auth-service
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
