apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ${DOCKER_REGISTRY}/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5005
          env:
            - name: PORT
              value: "5005"
            - name: NODE_ENV
              value: "production"
            - name: MONGOURL
              value: "mongodb://mongodb:27017/food-order"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: KAFKA_BROKERS
              value: "kafka:9092"
            - name: RESTAURANT_SERVICE_URL
              value: "http://restaurant-service:5006"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service:5007"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5005
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: food-delivery
spec:
  selector:
    app: order-service
  ports:
    - port: 5005
      targetPort: 5005
  type: ClusterIP
