apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: food-delivery
type: Opaque
data:
  # These values are base64 encoded
  # echo -n 'your_jwt_secret' | base64
  # Please replace these with proper secrets in a real environment
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0
  JWT_REFRESH_SECRET: eW91cl9yZWZyZXNoX3NlY3JldA==
  EMAIL_USER: eW91cl9lbWFpbA==
  EMAIL_PASS: eW91cl9wYXNzd29yZA==
